server:
  port: 24130
spring:
  application:
    name: 'Discussion'
  cassandra:
    keyspace-name: distcomp
    contact-points: localhost
    port: 9042
    username: cassandra
    password: cassandra
    local-datacenter: datacenter1
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    url: 'jdbc:cassandra://localhost:9042/distcomp?compliancemode=Liquibase&localdatacenter=datacenter1'
  datasource:
    driver-class-name: com.ing.data.cassandra.jdbc.CassandraDriver
    url: 'jdbc:cassandra://localhost:9042/distcomp'
    username: cassandra
    password: cassandra
