version: '3.4'

services:
  webapplicationdc1:
    image: ${DOCKER_REGISTRY-}webapplicationdc1
    build:
      context: .
      dockerfile: WebApplicationDC1/Dockerfile
    ports:
      - "24110:80"
    networks:
      mynet:
        ipv4_address: 172.16.0.10

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16